language: python
python:
    - 2.6
    - 2.7
    - 3.3
install:
    - pip install coverage coveralls --use-mirrors
    - pip install -e .
script:
    - coverage run --source=ghdiff -m zope.testrunner.__init__ --test-path=src
after_success:
    - coveralls
notifications:
    email: false
